# Generated by Django 5.1.2 on 2025-02-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_user_favoriteproduct_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Product',
            new_name='product',
        ),
    ]
